eConsentWeb/Controllers/ConsentController.cs
using eConsentWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Linq.Dynamic;
using System.Net;
using System.Linq.Expressions;
using eConsentWeb.Common;

namespace eConsentWeb.Controllers
{
    public class ConsentController : ParentController
    {
        private eConsentEntities db = new eConsentEntities();

        const string s_OptOut = "Opted Out";
        const string s_OptIn = "Opted In";

        public ActionResult Index()
        {
            ViewBag.Speciality = GenerateDDLSpeciality();
            ViewBag.Province = GenerateDDLProvince();
            ViewBag.City = GenerateDDLCity();

            return View();
        }

        // GET: Consent/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ConsentDetailsViewModel CDVM = new ConsentDetailsViewModel();
            
            CDVM.MSConsent = db.MS_eConsent.Where(w => w.doctorCode == id).FirstOrDefault();

            if (CDVM.MSConsent == null)
            {
                return HttpNotFound();
            }

            CDVM.HCPProfile = db.MS_eConsent_HCPProfile.Where(w => w.doctorCode == id).FirstOrDefault();
            CDVM.TRConsentList = db.TR_eConsent.Where(w => w.doctorCode == id).OrderByDescending(o => o.consentDate).ToList();

            return View(CDVM);
        }

        public void Export()
        {
            string filename = "[eConsent] Consent List Report_" + DateTime.Now.ToString("yyyyMMdd");

            if (((UserRole)Session["UserRole"]) == UserRole.Admin)
            {
                List<ConsentAdminExportModels> vAdmin = (
                    from m in db.MS_eConsent
                    join p in db.MS_eConsent_HCPProfile on m.doctorCode equals p.doctorCode into JoinedConsent
                    from p in JoinedConsent.DefaultIfEmpty()
                    join t in db.TR_eConsent on m.doctorCode equals t.doctorCode into JoinedTrxConsent
                    from t in JoinedTrxConsent.DefaultIfEmpty()
                    select new { m, p, t }).Select(s => new ConsentAdminExportModels
                    {
                        DOCTOR_CODE     = "=\"" + s.m.doctorCode + "\"",
                        NAME            = s.m.doctor,
                        SPECIALITY      = s.m.specialty,
                        CONSENT_LEVEL   = s.m.consentLevel,

                        STR             = s.p != null ? s.p.str                           : " - ",
                        GENDER          = s.p != null ? s.p.gender                        : " - ",
                        KOL_STATUS      = s.p != null ? s.p.KOLstatus                     : " - ",
                        PROVINCE        = s.p != null ? s.p.province                      : " - ",
                        CITY            = s.p != null ? s.p.city                          : " - ",
                        MAIN_PRACTICE   = s.p != null ? s.p.mainPractice                  : " - ",
                        PRACTICE1       = s.p != null ? s.p.practice1                     : " - ",
                        PRACTICE2       = s.p != null ? s.p.practice2                     : " - ",
                        MLD_STATUS      = s.p != null ? s.p.MLDstatus                     : " - ",
                        CONSENT_STATUS  = s.p != null ? s.p.consentStatus                 : " - ",

                        SERIES_ID       = s.t != null ? "=\"" + s.t.seriesID + "\""       : " - ",
                        CONSENT_CHANNEL = s.t != null ? s.t.consentChannels               : " - ",
                        CONSENT_DETAIL  = s.t != null ? "=\"" + s.t.consentDetails + "\"" : " - ",
                        OPT_STATUS      = s.t != null ? s.t.optStatus                     : " - ",
                        CONSENT_DATE    = s.t.consentDate ?? s.t.consentDate.Value
                    }
                ).ToList();

                ExportToFile(vAdmin, filename);
            }
            else
            {
                List<ConsentUserExportModels> vUser = (
                    from m in db.MS_eConsent
                    join p in db.MS_eConsent_HCPProfile on m.doctorCode equals p.doctorCode into JoinedConsent
                    from p in JoinedConsent.DefaultIfEmpty()
                    select new { m, p }).Select(s => new ConsentUserExportModels
                    {
                        DOCTOR_CODE    = "=\"" + s.m.doctorCode + "\"",
                        NAME           = s.m.doctor,
                        SPECIALITY     = s.m.specialty,
                        CONSENT_LEVEL  = s.m.consentLevel,

                        STR            = s.p != null ? s.p.str           : " - ",
                        GENDER         = s.p != null ? s.p.gender        : " - ",
                        KOL_STATUS     = s.p != null ? s.p.KOLstatus     : " - ",
                        PROVINCE       = s.p != null ? s.p.province      : " - ",
                        CITY           = s.p != null ? s.p.city          : " - ",
                        MAIN_PRACTICE  = s.p != null ? s.p.mainPractice  : " - ",
                        PRACTICE1      = s.p != null ? s.p.practice1     : " - ",
                        PRACTICE2      = s.p != null ? s.p.practice2     : " - ",
                        MLD_STATUS     = s.p != null ? s.p.MLDstatus     : " - ",
                        CONSENT_STATUS = s.p != null ? s.p.consentStatus : " - "
                    }
                ).ToList();

                ExportToFile(vUser, filename);
            }
        }

        

        public ActionResult ViewFile(string id)
        {
            TR_eConsent tr = db.TR_eConsent.Where(w => w.consentID == id).FirstOrDefault();

            if (tr == null)
            {
                return HttpNotFound();
            }

            MS_eConsent ms = db.MS_eConsent.Where(w => w.doctorCode == tr.doctorCode).FirstOrDefault();

            var filename = tr.pdfFileName;
            var sharedFolder = System.Configuration.ConfigurationManager.AppSettings["pdfFolder"];
            var doctorFolder = tr.doctorCode + "_" + ms.doctor;
            var path = sharedFolder + "\\" + doctorFolder + "\\" + filename;

            if (!System.IO.File.Exists(path))
            {
                return HttpNotFound();
            }
            
            return File(path, "application/pdf");
        }

        public SelectList GenerateDDLSpeciality()
        {
            var specialities = db.MS_eConsent.AsNoTracking().OrderBy(o => o.specialty).Select(s => s.specialty).Distinct().ToList();

            List<SelectListItem> ddlSpeciality = specialities
                        .Select(n =>
                        new SelectListItem
                        {
                            Value = n,
                            Text = n
                        }).ToList();

            return new SelectList(ddlSpeciality, "Value", "Text");
        }

        public SelectList GenerateDDLProvince()
        {
            var provinces = db.MS_eConsent_HCPProfile.AsNoTracking().OrderBy(o => o.province).Select(s => s.province).Distinct().ToList();

            List<SelectListItem> ddlProvince = provinces
                        .Select(n =>
                        new SelectListItem
                        {
                            Value = n,
                            Text = n
                        }).ToList();

            return new SelectList(ddlProvince, "Value", "Text");
        }

        public SelectList GenerateDDLCity()
        {
            var cities = db.MS_eConsent_HCPProfile.AsNoTracking().OrderBy(o => o.city).Select(s => s.city).Distinct().ToList();

            List<SelectListItem> ddlCity = cities
                        .Select(n =>
                        new SelectListItem
                        {
                            Value = n,
                            Text = n
                        }).ToList();

            return new SelectList(ddlCity, "Value", "Text");
        }

        [HttpPost]
        public ActionResult LoadConsent()
        {
            // datatables.js filter
            var draw           = Request.Form.GetValues("draw").FirstOrDefault();
            var start          = Request.Form.GetValues("start").FirstOrDefault();
            var length         = Request.Form.GetValues("length").FirstOrDefault();

            // custom filter
            var optStatusIn    = Request.Form.GetValues("opt_status_in").FirstOrDefault();
            var optStatusOut   = Request.Form.GetValues("opt_status_out").FirstOrDefault();
            var speciality     = Request.Form.GetValues("speciality[]");
            var province       = Request.Form.GetValues("province[]");
            var city           = Request.Form.GetValues("city[]");
            var consentChannel = Request.Form.GetValues("consent_channel[]");

            //Find Order Column
            var sortColumn     = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir  = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

            //Find Search Keyword
            var searchKey      = Request.Form.GetValues("search[value]").FirstOrDefault().ToLower();

            //Find Individual Search Keyword
            //var indSearchKey = Request.Form.GetValues("columns").ToList();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;


            List<ConsentIndexViewModel> v = (
                from m in db.MS_eConsent
                join p in db.MS_eConsent_HCPProfile

eConsentWeb/Views/Consent/Details.cshtml
@using eConsentWeb.Common
@model eConsentWeb.Models.ConsentDetailsViewModel

@{
    ViewBag.Title = "eConsent Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green-sharp">
                        <i class="fa fa-paper-plane-o font-green-sharp"></i>
                        <span class="caption-subject bold uppercase">eConsent details</span>
                        <span class="caption-helper hide"></span>
                    </div>
                </div>
                <div class="portlet-body">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.MSConsent.doctorCode)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.MSConsent.doctorCode)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.MSConsent.doctor)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.MSConsent.doctor)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.MSConsent.specialty)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.MSConsent.specialty)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.MSConsent.consentLevel)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.MSConsent.consentLevel)
                        </dd>

                        <br />

                        <dt>
                            @Html.DisplayNameFor(model => model.HCPProfile.str)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.HCPProfile.str)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.HCPProfile.gender)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.HCPProfile.gender)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.HCPProfile.KOLstatus)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.HCPProfile.KOLstatus)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.HCPProfile.province)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.HCPProfile.province)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.HCPProfile.city)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.HCPProfile.city)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.HCPProfile.mainPractice)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.HCPProfile.mainPractice)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.HCPProfile.practice1)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.HCPProfile.practice1)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.HCPProfile.practice2)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.HCPProfile.practice2)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.HCPProfile.MLDstatus)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.HCPProfile.MLDstatus)
                        </dd>
                    </dl>

                    @{
                        var icon = Model.TRConsentList[0].optStatus == "Opted In" ? "icon-like" : "icon-dislike";
                        var boxClass = Model.TRConsentList[0].optStatus == "Opted In" ? "green" : "red";

                    }
                    <div class="portlet box @boxClass hide">
                        <div class="portlet-title">
                            <div class="caption col-md-12">
                                <i class="@icon"></i>Latest Consent

                                <span class="label label-info pull-right uppercase bold">@Model.TRConsentList[0].optStatus</span>
                            </div>
                        </div>
                        <div class="portlet-body pad15T">
                            <div class="form-horizontal">
                               <div class="row">
                                   <div class="col-md-6">
                                       <div class="form-group">
                                           <label class="control-label col-md-4"><b>Series ID</b></label>
                                           <div class="col-md-8 pad7T">
                                               @Model.TRConsentList[0].seriesID
                                           </div>
                                       </div>
                                       <div class="form-group">
                                           <label class="control-label col-md-4"><b>Consent Channel</b></label>
                                           <div class="col-md-8 pad7T">
                                               @Model.TRConsentList[0].consentChannels
                                           </div>
                                       </div>
                                   </div>
                                   <div class="col-md-6">
                                       <div class="form-group">
                                           <label class="control-label col-md-4"><b>Consent Details</b></label>
                                           <div class="col-md-8 pad7T">
                                               @Model.TRConsentList[0].consentDetails
                                           </div>
                                       </div>
                                       <div class="form-group">
                                           <label class="control-label col-md-4"><b>Consent Date</b></label>
                                           <div class="col-md-8 pad7T">
                                               @Model.TRConsentList[0].consentDate
                                           </div>
                                       </div>
                                   </div>
                               </div>
                            </div>
                        </div>
                    </div>

                    @if (((UserRole)Session["UserRole"]) != UserRole.AdminEntry && ((UserRole)Session["UserRole"]) != UserRole.AdminSystem)
                    {
                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-list"></i>Consent Files
                                </div>
                            </div>
                            <div class="portlet-body pad15T">
                                <table class="table table-striped table-bordered table-hover dataTable" id="consent-trx">
                                    <thead>
                                        <tr>
                                            <th>
                                                Series ID
                                            </th>
                                            <th>
                                                Consent Channel
                                            </th>
                                            <th>
                                                Consent Details
                                            </th>
                                            <th>
                                                Opt Status
                                            </th>
                                            <th>
                                                Consent Date
                                            </th>
                                            @if (((UserRole)Session["UserRole"]) == UserRole.Admin)
                                            {
                                                <th style="min-width: 50px">
                                                    PDF
                                                </th>
                                            }
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.TRConsentList)
                                        {
                                            var cssClass = item.optStatus == "Opted In" ? "success" : "danger";
                                            <tr class="@cssClass">
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.seriesID)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.consentChannels)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.consentDetails)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.optStatus)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.consentDate)
                                                </td>

                                                @if (((UserRole)Session["UserRole"]) == UserRole.Admin)
                                                {
                                                    <td class="text-center">
                                                        <a href="@Url.Action("ViewFile", "Consent", new { id = item.consentID })" target="_blank" title="See PDF" class="btn yellow btn-xs btn-edit">
                                                            <i class="fa fa-file-pdf-o"></i>
                                                        </a>
                                                    </td>
                                                }
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    }
                    <p>
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn default mrg15L" })
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
           
        });
    </script>
}