eConsentWeb/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eConsentWeb;
using eConsentWeb.Common;
using System.Data.Entity.Validation;
using Cryptography;

namespace eConsentWeb.Controllers
{
    public class UserManagementController : Controller
    {
        private eConsentEntities db = new eConsentEntities();
        private AES_Cryptography crypto = new AES_Cryptography();

        // GET: UserManagement
        public ActionResult Index()
        {
            var uSERs = db.MS_User.Include(u => u.MS_User2);
            return View(uSERs.ToList());
        }

        // GET: UserManagement/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MS_User uSER = db.MS_User.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            return View(uSER);
        }

        // GET: UserManagement/Create
        public ActionResult Create()
        {
            GenerateDDL();

            return View();
        }

        // POST: UserManagement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MS_User uSER)
        {
            MS_User chkUser = db.MS_User.Where(w => w.username == uSER.username).FirstOrDefault();
            GenerateDDL();

            if (chkUser != null)
            {
                ModelState.AddModelError("username", "Username is already exists");
            }

            if (ModelState.IsValid)
            {
                uSER.password = crypto.encryptString(UserHelper.DefaultPassword);
                uSER.createdBy = Convert.ToInt16(Session["UserID"].ToString());
                uSER.createdDate = DateTime.Now;

                try
                {
                    db.MS_User.Add(uSER);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "Create New User Failed";
                    LogSystem.ErrorLog(ex, null);
                    //throw;
                    return View(uSER);
                }

                return RedirectToAction("Index");
            }
            
            return View(uSER);
        }

        // GET: UserManagement/Edit/5
        public ActionResult Edit(int? id)
        {
            GenerateDDL();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MS_User uSER = db.MS_User.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }

            return View(uSER);
        }

        // POST: UserManagement/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MS_User uSER, bool IsReset)
        {
            GenerateDDL();

            if (ModelState.IsValid)
            {
                if (IsReset)
                    uSER.password = crypto.encryptString(UserHelper.DefaultPassword);
                
                try
                {
                    db.Entry(uSER).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "Update User Failed";
                    LogSystem.ErrorLog(ex, null);
                    //throw;
                    return View(uSER);
                }

                return RedirectToAction("Index");
            }
            
            return View(uSER);
        }

        // GET: UserManagement/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    MS_User uSER = db.MS_User.Find(id);
        //    if (uSER == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(uSER);
        //}

        // POST: UserManagement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MS_User uSER = db.MS_User.Find(id);
            db.MS_User.Remove(uSER);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void GenerateDDL()
        {
            ViewBag.Roles = EnumHelper.ToOrderedSelectList<UserRole>();
            ViewBag.Statuses = EnumHelper.ToOrderedSelectList<Status>();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eConsentWeb/Views/UserManagement/Create.cshtml
@model eConsentWeb.MS_User

@{
    ViewBag.Title = "Create New User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green-sharp">
                        <i class="icon-user-follow font-green-sharp"></i>
                        <span class="caption-subject bold uppercase">New User</span>
                        <span class="caption-helper hide"></span>
                    </div>
                </div>
                <div class="portlet-body form">
                    <div id="dv-alert"></div>
                    
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                         
                            <div class="form-group">
                                @Html.LabelRequiredFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelRequiredFor(model => model.fullname, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.fullname, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.fullname, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelRequiredFor(model => model.role, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @*@Html.EditorFor(model => model.role, new { htmlAttributes = new { @class = "form-control" } })*@
                                    @Html.DropDownListFor(model => model.role, new List<SelectListItem>(ViewBag.Roles), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.role, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelRequiredFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelRequiredFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.status, new List<SelectListItem>(ViewBag.Statuses), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-sm-12">
                                        @if (ViewBag.Error != null && ViewBag.Error != "")
                                        {
                                            <div class='alert alert-danger text-center' role='alert'>
                                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                                <b>@ViewBag.Error</b>
                                            </div>
                                        }

                                        @if (ViewBag.Success != null && ViewBag.Success != "")
                                        {
                                            <div class='alert alert-success text-center' role='alert'>
                                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                                <b>@ViewBag.Success</b>
                                            </div>
                                        }
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-offset-2 col-md-10">
                                        @*<input type="submit" value="Create" class="btn btn-default" />*@
                                        <button type="submit" class="btn btn-success" id="btn-save">
                                            <i class="fa fa-check"></i> 
                                            Save Changes
                                        </button>
                                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn default" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

eConsentWeb/Views/UserManagement/Delete.cshtml
@using eConsentWeb.Common
@model eConsentWeb.MS_User

@{
    ViewBag.Title = "Delete User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green-sharp">
                        <i class="icon-user-unfollow font-green-sharp"></i>
                        <span class="caption-subject bold uppercase">Delete User (@Model.USERNAME - @Model.FULLNAME)</span>
                        <span class="caption-helper hide"></span>
                    </div>
                </div>
                <div class="portlet-body form">
                    <div id="dv-alert"></div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.USERNAME)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.USERNAME)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.FULLNAME)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.FULLNAME)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.ROLE)
                        </dt>

                        <dd>
                            @UserHelper.GetUserRole(Model.ROLE)
                        </dd>
                        
                        <dt>
                            @Html.DisplayNameFor(model => model.EMAIL)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.EMAIL)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.STATUS)
                        </dt>

                        <dd>
                            @if (Model.STATUS == 0)
                            {
                                <span class="label label-danger"> Inactive </span>
                            }
                            else
                            {
                                <span class="label label-success"> Active </span>
                            }
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CREATEDDATE)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CREATEDDATE)
                        </dd>

                        <dt>
                            Created By
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.USER2.USERNAME)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            @*<input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Back to List", "Index")*@
                            <div class="col-md-offset-2 col-md-10">
                                @*<input type="submit" value="Create" class="btn btn-default" />*@
                                <button type="submit" class="btn btn-danger" id="btn-save">
                                    <i class="fa fa-trash-o"></i>
                                    Delete
                                </button>
                                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn default" })
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

eConsentWeb/Views/UserManagement/Details.cshtml
@using eConsentWeb.Common
@model eConsentWeb.MS_User

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>USER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.USERNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FULLNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FULLNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ROLE)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.ROLE)*@
            @(((UserRole)Model.ROLE).GetDescription())
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PASSWORD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PASSWORD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STATUS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CREATEDDATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CREATEDDATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USER2.USERNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USER2.USERNAME)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.USERID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

eConsentWeb/Views/UserManagement/Edit.cshtml
@model eConsentWeb.MS_User

@{
    ViewBag.Title = "Edit User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green-sharp">
                        <i class="icon-user-following font-green-sharp"></i>
                        <span class="caption-subject bold uppercase">Edit User (@Model.username - @Model.fullname)</span>
                        <span class="caption-helper hide"></span>
                    </div>
                </div>
                <div class="portlet-body form">
                    <div id="dv-alert"></div>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                         
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.id)
                            @Html.HiddenFor(model => model.password)
                            @Html.HiddenFor(model => model.createdBy)

                            <div class="form-group">
                                @Html.LabelRequiredFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelRequiredFor(model => model.fullname, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.fullname, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.fullname, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelRequiredFor(model => model.role, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.role, new List<SelectListItem>(ViewBag.Roles), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.role, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelRequiredFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelRequiredFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.status, new List<SelectListItem>(ViewBag.Statuses), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Created By", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10 pad-top-7">
                                    @Html.DisplayFor(model => model.MS_User2.username)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Created Date", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10 pad-top-7">
                                    @Html.DisplayFor(model => model.createdDate)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("IsReset", "Reset Password?", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10" style="padding-top: 7px;">
                                    <label class="mt-checkbox mt-checkbox-outline">
                                        (Check if Reset Password)
                                        @*<input type="checkbox" name="IsReset">*@
                                        @Html.CheckBox("IsReset", false)
                                        <span></span>
                                    </label>
                                </div>
                            </div>

                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-sm-12">
                                        @if (ViewBag.Error != null && ViewBag.Error != "")
                                        {
                                            <div class='alert alert-danger text-center' role='alert'>
                                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                                <b>@ViewBag.Error</b>
                                            </div>
                                        }

                                        @if (ViewBag.Success != null && ViewBag.Success != "")
                                        {
                                            <div class='alert alert-success text-center' role='alert'>
                                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                                <b>@ViewBag.Success</b>
                                            </div>
                                        }
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-offset-2 col-md-10">
                                        @*<input type="submit" value="Create" class="btn btn-default" />*@
                                        <button type="submit" class="btn btn-success" id="btn-save">
                                            <i class="fa fa-check"></i>
                                            Save Changes
                                        </button>
                                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn default" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

eConsentWeb/Views/UserManagement/Index.cshtml
@using eConsentWeb.Common
@model IEnumerable<eConsentWeb.MS_User>

@{
    ViewBag.Title = "User List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-green-sharp">
                        <i class="icon-users font-green-sharp"></i>
                        <span class="caption-subject bold uppercase">User List</span>
                        <span class="caption-helper hide"></span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div id="dv-alert"></div>
                    <div class="table-toolbar">
                        <div class="row">
                            <div class="col-md-6">
                                <a class="btn sbold green" id="btn-add" href="@Url.Action("Create", "UserManagement")">
                                    <i class="fa fa-plus"></i>
                                    Add New User
                                </a>
                            </div>
                        </div>
                    </div>
                    <table class="table table-striped table-bordered table-hover dataTable" id="user-list">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.username)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.fullname)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.role)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.email)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.status)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.createdDate)
                                </th>
                                <th>
                                    Created By
                                </th>
                                <th style="min-width: 50px"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.username)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.fullname)
                                    </td>
                                    <td>
                                        @*@UserHelper.GetUserRole(item.ROLE)*@
                                        @(((UserRole)item.role).GetDescription())
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.email)
                                    </td>
                                    <td>
                                        @if (item.status > 0)
                                        {
                                            <span class="label label-success"> Active </span>
                                        }
                                        else
                                        {
                                            <span class="label label-danger"> Inactive </span>
                                        }
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.createdDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MS_User2.username)
                                    </td>
                                    <td class="text-center">
                                        <a href="@Url.Action("Edit", "UserManagement", new { id = item.id })" title="Edit" class="btn green btn-xs btn-edit">
                                            <i class="fa fa-pencil"></i>
                                        </a>

                                        @*@if(Session["UserID"].ToString() != item.USERID.ToString())
                                        {
                                            <a href="@Url.Action("Delete", "UserManagement", new { id = item.USERID })" title="Delete" class="btn red btn-xs btn-disable">
                                                <i class="fa fa-remove"></i>
                                            </a>
                                        }*@

                                        @*@Html.ActionLink("Edit", "Edit", new { id = item.USERID }) |
                                        @Html.ActionLink("Details", "Details", new { id = item.USERID }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.USERID })*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>