eConsentWeb/Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eConsentWeb.Common;
using eConsentWeb.Models;
using System.Data;
using Newtonsoft.Json;
using System.Net;
using System.Data.Entity;
using System.Web.UI;
using eConsentWeb.Service;

namespace eConsentWeb.Controllers
{
    public class CampaignController : ParentController
    {
        private DigitalDashboardEntities db = new DigitalDashboardEntities();

        private string vCampaignHeader = "vCampaignHeader";
        private string vCampaignWebinarDetail = "vCampaignWebinarDetail";
        private string vCampaignEmailDetail = "vCampaignEmailDetail";

        #region Generate DDL
        private MultiSelectList GenerateDDLBusinessUnit(string[] selectedValue)
        {
            var data = db.Mst_BU.Where(w => w.Status.Equals(((int)Status.Active).ToString())).ToList();

            List<SelectListItem> items = data
                        .Select(n =>
                        new SelectListItem
                        {
                            Value = n.BUID.ToString(),
                            Text = n.BU
                        }).ToList();

            return new MultiSelectList(items, "Value", "Text", selectedValue);
        }

        private MultiSelectList GenerateDDLBrand(string[] selectedValue)
        {
            var data = db.Mst_Brand.Where(w => w.Status.Equals(((int)Status.Active).ToString())).ToList();

            List<SelectListItem> items = data
                        .Select(n =>
                        new SelectListItem
                        {
                            Value = n.BrandID.ToString(),
                            Text = n.BrandName
                        }).ToList();

            return new MultiSelectList(items, "Value", "Text", selectedValue);
        }

        private SelectList GenerateDDLCampaignStatus(string selectedValue)
        {
            var data = EnumHelper.ToOrderedSelectList<CampaignStatus>();

            return new SelectList(data, "Value", "Text", selectedValue);
        }

        private MultiSelectList GenerateDDLChannel(string[] selectedValue)
        {
            var data = db.Mst_Channel.Where(w => w.Status.Equals(((int)Status.Active).ToString())).ToList();

            List<SelectListItem> items = data
                        .Select(n =>
                        new SelectListItem
                        {
                            Value = n.ChannelID.ToString(),
                            Text = n.Channel
                        }).ToList();

            return new MultiSelectList(items, "Value", "Text", selectedValue);
        }

        private MultiSelectList GenerateDDLTargetAudience(string[] selectedValue)
        {
            var data = db.Mst_Target_Audience.Where(w => w.Status.Equals(((int)Status.Active).ToString())).ToList();

            List<SelectListItem> items = data
                        .Select(n =>
                        new SelectListItem
                        {
                            Value = n.TargetAudienceID.ToString(),
                            Text = n.TargetAudience
                        }).ToList();

            return new MultiSelectList(items, "Value", "Text", selectedValue);
        }

        private void GenerateDDL(string campaignID)
        {
            ViewBag.Roles = EnumHelper.ToOrderedSelectList<UserRole>();
            ViewBag.Statuses = EnumHelper.ToOrderedSelectList<Status>();

            //ViewBag.BU = db.Mst_BU.Select(s => new SelectListItem
            //{
            //    Text = s.BU,
            //    Value = s.BUID.ToString()
            //});

            var BusinessUnit = db.Campaign_Header.Where(w => w.CampaignID == campaignID).Select(s => s.BUID.ToString()).ToArray();
            ViewBag.BusinessUnit = GenerateDDLBusinessUnit(BusinessUnit);

            var BrandList = db.Campaign_Brand.Where(w => w.CampaignID == campaignID).Select(s => s.BrandID.ToString()).ToArray();
            ViewBag.Brand = GenerateDDLBrand(BrandList);

            var TargetAudience = db.Campaign_TargetAudience.Where(w => w.CampaignID == campaignID).Select(s => s.TargetAudienceID.ToString()).ToArray();
            ViewBag.TargetAudience = GenerateDDLTargetAudience(TargetAudience);


        }
        #endregion

        public ActionResult Index(AdvancedSearchRequest request)
        {
            ViewBag.BusinessUnit = GenerateDDLBusinessUnit(request.bu);
            ViewBag.Brand = GenerateDDLBrand(request.b);
            ViewBag.CampaignStatus = GenerateDDLCampaignStatus(request.s);
            ViewBag.Channel = GenerateDDLChannel(request.c);
            ViewBag.TargetAudience = GenerateDDLTargetAudience(request.ta);

            return View(request);
        }

        public ActionResult Create()
        {
            //if (ID ==0)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}

            CampaignModel cm = new CampaignModel();

            //var campaignHeader = db.Campaign_Header.Where(w => w.ID == ID).FirstOrDefault();

            //if (campaignHeader == null)
            //{
            //    return HttpNotFound();
            //}
            //cm.ID = campaignHeader.ID;
            //cm.CampaignID = campaignHeader.CampaignID;
            //cm.CampaignName = campaignHeader.CampaignName;
            //cm.StartDate = campaignHeader.StartDate;
            //cm.EndDate = campaignHeader.EndDate;
            //cm.Description = campaignHeader.CampaignDescription;

            GenerateDDL("");

            return View(cm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CampaignModel cm)
        {
            if (ModelState.IsValid)
            {
                using (var dbTran = db.Database.BeginTransaction())
                {
                    try
                    {
                        Campaign_Header campaign_Header = new Campaign_Header();
                        //campaign_Header = db.Campaign_Header.Where(w => w.ID == cm.ID).FirstOrDefault();
                        campaign_Header.CampaignID = GenerateCampaignID();
                        campaign_Header.CampaignName = cm.CampaignName;
                        campaign_Header.BUID = Int32.Parse(cm.BusinessUnitID);
                        campaign_Header.CampaignDescription = cm.Description;
                        campaign_Header.StartDate = cm.StartDate;
                        campaign_Header.EndDate = cm.EndDate;
                        campaign_Header.Status = CheckCampaignDetail(cm.CampaignID) == true ? "2" : "1";
                        campaign_Header.Date_Updated = DateTime.Now;
                        campaign_Header.User_Updated = Session["UserName"].ToString();

                        db.Campaign_Header.Add(campaign_Header);
                        db.SaveChanges();

                        foreach (var brand in cm.BrandID)
                        {
                            if (CheckBrandIsExist(campaign_Header.CampaignID, brand))
                            {
                                continue;
                            }
                            Campaign_Brand cb = new Campaign_Brand();
                            cb.CampaignID = campaign_Header.CampaignID;
                            cb.BrandID = brand;
                            cb.Status = ((int)Status.Active).ToString();
                            cb.Date_Updated = DateTime.Now;
                            cb.User_Updated = Session["UserName"].ToString();

                            db.Campaign_Brand.Add(cb);
                            db.SaveChanges();
                        }

                        foreach (var taID in cm.TargetAudienceID)
                        {
                            if (CheckTargetAudIsExist(campaign_Header.CampaignID, taID))
                            {
                                continue;
                            }

                            Campaign_TargetAudience ta = new Campaign_TargetAudience();
                            ta.CampaignID = campaign_Header.CampaignID;
                            ta.TargetAudienceID = taID;
                            ta.Status = ((int)Status.Active).ToString();
                            ta.Date_Updated = DateTime.Now;
                            ta.User_Updated = Session["UserName"].ToString();

                            db.Campaign_TargetAudience.Add(ta);
                            db.SaveChanges();
                        }
                        dbTran.Commit();
                        return RedirectToAction("Assign", new { id = campaign_Header.CampaignID });
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Error = "Assign Failed";
                        LogSystem.ErrorLog(ex, null);
                        dbTran.Rollback();
                        GenerateDDL(cm.CampaignID);
                        return View(cm);
                    }
                }


            }
            GenerateDDL(cm.CampaignID);

            return View(cm);
        }

        public ActionResult AdvancedSearch(AdvancedSearchRequest request)
        {
            ViewBag.BusinessUnit = GenerateDDLBusinessUnit(request.bu);
            ViewBag.Brand = GenerateDDLBrand(request.b);
            ViewBag.CampaignStatus = GenerateDDLCampaignStatus(request.s);
            ViewBag.Channel = GenerateDDLChannel(request.c);
            ViewBag.TargetAudience = GenerateDDLTargetAudience(request.ta);

            return View(request);
        }

        public ActionResult Details(string id)
        {
            Campaign_Header header = db.Campaign_Header.Where(w => w.CampaignID.Equals(id) && !w.Status.Equals(((int)CampaignStatus.Deleted).ToString())).FirstOrDefault();

            if (header == null)
            {
                return HttpNotFound();
            }

eConsentWeb/Views/Campaign/_Email.cshtml
@model eConsentWeb.Models.CampaignModel

@*<div class="portlet light bordered tasks-widget">
    <div class="portlet-title">
        <div class="caption caption-md">

            <span class="caption-helper font-blue-madison bold uppercase">Email Campaign</span>

        </div>
        <div class="inputs">
            <div class="portlet-input input-small input-inline">
                <div class="input-icon right">
                    
                    <a href="#modal-emailchannel" data-toggle="modal" onclick=" LoadEmailChannel();" title="Add" id="addwebinarchannel" class="btn sbold green-sharp">Browse</a>
                </div>
            </div>
        </div>

    </div>
    <div class="portlet-body">
        <div class="task-content">
            <ul class="feeds"  id="email-content">

            </ul>


        </div>

    </div>
</div>*@


<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-envelope-o"></i>Email HO
        </div>
        <div class="actions">
            <a href="#modal-emailchannel" data-toggle="modal" onclick="LoadEmailChannel();" title="Add" id="addwebinarchannel" class="btn default">
                <i class="fa fa-search"></i>
                Browse
            </a>
        </div>
    </div>
    <div class="portlet-body pad15T">
        <table class="table table-striped table-bordered table-hover dataTable" id="channel-email">
            <thead>
                <tr>
                    <th>
                        Email ID
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Sent Date
                    </th>
                    <th>
                        Source
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Emails)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.WebinarID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Topic)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EventDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Source)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>

    

    function LoadEmail(id) {

        //list email campaign by campaign ID
        var url = "@Url.Action("LoadEmailCampaign", "Campaign")/"+id;
        

        $.ajax({
            url: url,
            method: 'GET',
            async: true,
           
            success: function (response) {
                var div1 = "";
                if (response.status == true) {
                   
                    console.log(response.data.length);

                    console.log(response.data);
                    response.data.forEach(function (d) {
                        div1 += "<li>" + d.Topic + "</li>";
                    });

                    $("#email-content").html(div1);


                } else {
                    alert("Sory something worng ");
                }

            },
            error: function (data, status, xhr) {
                
                console.log(data + "---" + xhr);

            }
        });
        return false;


    }


    
</script>

eConsentWeb/Views/Campaign/_EmailDataTable.cshtml
<div id="modal-emailchannel" class="modal " data-width="800">

    

    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title">Add Email Channel</h4>
        </div>
        <div class="modal-body">

           
                    @using (Html.BeginForm("CreateEmailChannel", "Campaign", FormMethod.Post, new { id = "formsubmitMail", @class = "form-horizontal", @autocomplete = "off" }))
                    {
                            <table class="table table-striped table-checkable table-bordered" id="email-list-add">
                                <thead>
                                    <tr>
                                        <th class="table-checkboxmail select-checkbox">
                                            <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                                <input type="checkbox" id="select_allmail" name="select_allmail" value="1" class="group-checkable" data-set="#email-list .checkboxes" />
                                                <input type="hidden" id="idcampaignmail" name="campaignId" />

                                                <span></span>
                                            </label>
                                        </th>

                                        <th>
                                            Topic ID
                                        </th>
                                        <th>
                                            Topic
                                        </th>
                                        <th>
                                            Sent Date
                                        </th>
                                        <th>
                                            Source
                                        </th>

                                    </tr>
                                </thead>
                                <tbody>
                                    <tr></tr>
                                </tbody>
                            </table>
                      
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    @*<button type="submit" class="btn green">Submit</button>*@
                                    <button type="submit" id="btnsubmitmail" data-loading-text="<i class='fa fa-spinner fa-spin '></i> Processing Data" class="btn green mt-ladda-btn ladda-button" data-style="slide-left">
                                        <span class="ladda-label">Submit</span>
                                    </button>
                                    <button type="button" class="btn default" data-dismiss="modal">Cancel</button>
                                </div>
                            </div>
                        </div>
                    }
                   

           

        </div>
        <div class="modal-footer">

        </div>
    </div>
    
</div>

<style>
    table tr {
        cursor: pointer;
    }
</style>

<script>
    function LoadEmailChannel() {
        //document.getElementById("select_allmail").checked = false;
        var idcampaign = $("#txt-campaign-id").val();
        $("#idcampaignmail").val(idcampaign);
        var rows_selected = [];
        var url = "@Url.Action("LoadEmailDataTableV2", "Campaign")/" + idcampaign;
        var tableEmail = $("#email-list-add").DataTable({
            "processing": true, // for show progress bar
            "serverSide": false, // for process server side
            "destroy": true,
            "filter": true,
            'checkboxes': {
                'selectRow': true
            },
            select: {
                style: 'multi'
            },
            "ajax": {
                url: url,
                type: "POST",
                datatype: "json",
            },
            "columns": [
                { "data": "WebinarID", "name": "WebinarID", "autoWidth": true, "orderable": false, className: 'select-checkbox' },
                { "data": "WebinarID", "name": "WebinarID", "autoWidth": true, "orderable": false },
                { "data": "Topic", "name": "Topic", "autoWidth": true },
                { "data": "EventDate", "name": "EventDate", "autoWidth": true },
                { "data": "Source", "name": "Source", "autoWidth": true }
            ],
            rowCallback: function (row, data, full, meta, index) {
                // convert EventDate to dd/mm/yyyy
                if (data["EventDate"]) {
                    var today = eval(data["EventDate"].replace(/\/Date\((\d+)\)\//gi, "new Date($1)"));
                    var dd = String(today.getDate()).padStart(2, '0');
                    var mm = String(today.getMonth() + 1).padStart(2, '0');
                    var yyyy = today.getFullYear();
                    date = dd + '/' + mm + '/' + yyyy;
                    $('td ', row).eq(3).html(date);
                }
            },
            initComplete: function () {
                tableEmail.rows().every(function (rowIdx, tableLoop, rowLoop) {
                    var data = this.data();

                    console.log(rowIdx + ": " + data.WebinarID + "|" + data.isChecked);
                    var row = $(this.node());
                    if (data.isChecked == true) {
                        $('td', row).eq(0).html('');
                        tableEmail.rows(row).select();
                    } else {
                        $('td', row).eq(0).html('');
                    }
                });
            }
        });

        // select all event
        tableEmail.on("click", "th.select-checkbox, #select_allmail", function () {
            if ($("th.select-checkbox").hasClass("selected")) {
                tableEmail.rows().deselect();
                $("th.select-checkbox").removeClass("selected");
                $("#select_allmail").prop("checked", false);
            } else {
                tableEmail.rows().select();
                $("th.select-checkbox").addClass("selected");
                $("#select_allmail").prop("checked", true);
            }
        }).on("select deselect", function () {
            ("Some selection or deselection going on")
            if (tableEmail.rows({
                selected: true
            }).count() !== tableEmail.rows().count()) {
                $("th.select-checkbox").removeClass("selected");
                $("#select_allmail").prop("checked", false);
            } else {
                $("th.select-checkbox").addClass("selected");
                $("#select_allmail").prop("checked", true);
            }
        });

        $('#btnsubmitmail').click(function () {

            var form = $("#formsubmitMail");

            tableEmail.rows({ selected: true }).every(function (rowIdx, tableLoop, rowLoop) {
                var data = this.data();

                console.log(data);

                $(form).append(
                    $('<input>')
                        .attr('type', 'hidden')
                        .attr('name', 'ids[]')
                        .val(data["WebinarID"])
                );
            });

            $.ajax({
                type: form.attr("method"),
                url: form.attr("action"),
                data: form.serialize(),
                async: false,
                success: function (response) {
                    console.log(response);
                    if (response.success != false) {
                        location.reload(0)

                    }
                    else {
                        alert(response.msg);
                    }

                },
                error: function (data, status, xhr) {
                    console.log(data + "---" + xhr);
                }

            })

            return false;
        });
    }
</script>

eConsentWeb/Views/Campaign/_Webinar.cshtml
@model eConsentWeb.Models.CampaignModel

@*<div class="portlet light bordered tasks-widget">
    <div class="portlet-title">
        <div class="caption caption-md">

            <span class="caption-helper font-blue-madison bold uppercase">Webinar Campaign</span>

        </div>
        <div class="inputs">
            <div class="portlet-input input-small input-inline">
                <div class="input-icon right">
                    <a href="#modal-webinarchannel" data-toggle="modal" onclick=" LoadWebinarChannel();" title="Add" id="addwebinarchannel" class="btn sbold green-sharp">Browse</a>
                </div>
            </div>
        </div>

    </div>
    <div class="portlet-body">
        <div class="task-content" >

            <ul class="feeds" id="webinar-content">

            </ul>

        </div>

    </div>
</div>*@


<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-video-camera"></i>Webinar
        </div>
        <div class="actions">
            <a href="#modal-webinarchannel" data-toggle="modal" onclick="LoadWebinarChannel();" title="Add" id="addwebinarchannel" class="btn default">
                <i class="fa fa-search"></i>
                Browse
            </a>
        </div>
    </div>
    <div class="portlet-body pad15T">
        <table class="table table-striped table-bordered table-hover dataTable" id="channel-webinar">
            <thead>
                <tr>
                    <th>
                        Webinar ID
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Event Date
                    </th>
                    <th>
                        Source
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Webinars)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.WebinarID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Topic)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EventDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Source)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>

    

    function LoadWebinar(id) {

        
        var url = "@Url.Action("LoadWebinarCampaign", "Campaign")/"+id;
        

        $.ajax({
            url: url,
            method: 'GET',
            async: true,
           
            success: function (response) {
               
                var count = 0;
               

                var div1 = "";
                if (response.status == true) {
                   
                    console.log(response.data);
                    response.data.forEach(function (d) {
                        div1 += "<li>" + d.Topic + "</li>";
                    });

                    $("#webinar-content").html(div1);
                   

                } else {
                    alert("Sory something worng ");
                }

            },
            error: function (data, status, xhr) {
                //alert(err)
                //alert(@ViewBag.msg);
                //$("#idalert").html('<div id="idalert" class="alert alert-danger">'
                //    + '  <button class="close" data-dismiss="alert" type="button"></button>'
                //    + ' <span>Sory something wrong. Please try again at another time or contact adminsitrator! </span>'
                //    + '  </div>');

                console.log(data + "---" + xhr);

            }
        });
        return false;


    }


    
</script>